version: '3'

services:
    web:
        image: levidurfee/nginx:v3
        deploy:
            replicas: 1
            restart_policy:
              condition: on-failure
        ports:
          - "80:80"
        networks:
            - webnet
        depends_on:
          - php
    php:
        image: levidurfee/php:v4d
        deploy:
            replicas: 10
            restart_policy:
              condition: on-failure
        ports:
          - "9000:9000"
        networks:
            - webnet


networks:
  webnet:
